repositories:
- name: incubator
  url: https://charts.helm.sh/incubator/
releases:
- name: raw1
  chart: incubator/raw
  version: 0.1.0
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        foo: FOO
  strategicMergePatches:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        bar: BAR
