repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator/
releases:
  - name: some-local-chart
    chart: ./chart
  - name: raw1
    chart: incubator/raw
    version: 0.1.0
    values:
      - resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: raw1
              namespace: default
            data:
              foo: FOO
